version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /workspace/node_modules
      - .:/workspace
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /workspace/node_modules
      - .:/workspace
    command: ["npm", "run", "test"]
