# Monik-Reeves
# Use `-f` flag when building image form custom Dockerfile like this one
# Use `docker build -f Dockerfile.dev .`

FROM node:16-alpine
WORKDIR /home/workspace 
COPY package.json . 
RUN npm install
COPY . . 
CMD ["npm" , "start"]